### ISSUE TITLE
Remove Bootstrap CSS

### ISSUE THREAD

**Issue by loikein** [loikein/hugo-theme-diary#5]
While doing https://github.com/loikein/hugo-theme-diary/issues/2, I found that a lot of night theme problems were caused by the Bootstrap CSS.

Files to change:

https://github.com/loikein/hugo-theme-diary/blob/main/layouts/partials/head.html#L87-L101

https://github.com/loikein/hugo-theme-diary/blob/1fd1229e0d941057b2c1b1189972f1e1e16c3f4d/layouts/partials/head.html#L129

https://github.com/loikein/hugo-theme-diary/tree/main/static/vendor/css/

**Comment by loikein** [comment]
For the CSS, maybe keep the classes, and add helper styles.

**Comment by nielsnl68** [comment]
Hi @loikein. I saw your PR on the Diary theme site with the modifications on the SASS files.
I started using Hugo and found the Diary theme very appealing, The only thing I'm not happy about is the used version (4.3.1) of bootstrap and visiting your repo i saw this post. Good that you already thinking about it.
 
Based on the work you recently did, do you know how heavily this theme is using the bootstrap anyway? 
Wold it make sense to upgrade to the latest version? 
Or is it better to remove it as you suggested above? 

At one side i like the option to modify the views via the bootstrap classes but as end user you can only use the Markdown options anyway.

**Comment by loikein** [comment]
Hi @nielsnl68. Thank you for your interest in my fork. I would like to clarify that I am not a professional web developer, and I have never worked with Bootstrap myself.

That being said, based on what I have messed with in this theme, I feel like the Bootstrap CSS is doing more harm than good. At some point during writing that PR, I remember trying completely commenting out the Bootstrap CSS, and only very few things broke (not that nothing broke, otherwise I would have just deleted it at that point). 

So I do believe that removing it may be ideal. It's just that I have a lot on my plate right now, and I have not gotten around to it…

**Comment by nielsnl68** [comment]
Thanks, for your reply. Sadly i have switched to *mkdocs* the MK options with **Hugo** where not fitting the needs we have.

**Comment by loikein** [comment]
@nielsnl68 If MkDocs better suits your needs, then I am indeed very happy for you. I also have been keeping an eye on it for a while, but I wonder how does its building speed compare to Hugo, or Sphinx, since MkDocs is also written in Python.
